"""Add phone verification fields

Revision ID: 65e245ac851b
Revises: 6eea547d6c95
Create Date: 2025-06-13 18:30:18.733333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e245ac851b'
down_revision = '6eea547d6c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
